class ResponsePracticumException(Exception):
    """Исключение возникает из-за ошибок в запросе к сервису."""
    pass
